# Nombre del proyecto
spring.application.name=sistema-vehiculos

# PUERTO DINÁMICO (Esto es lo que Railway necesita)
server.port=${PORT:8080}

# Configuración de Base de Datos H2 (En memoria para el parcial)
spring.datasource.url=jdbc:h2:mem:vehiculosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console (Para que puedas entrar a ver las tablas localmente)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console