spring.application.name=sistema-vehiculos
# Esta línea es la más importante para Railway:
server.port=${PORT:8080}

# Configuración para que la base de datos H2 no dé problemas en la nube
spring.datasource.url=jdbc:h2:mem:vehiculosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true